let mongoose = require('mongoose');
let Schema = mongoose.Schema;

let depositSchema = new Schema({
    //deposit id auto generated by mongo
    transaction: [{
        amount: Number,
        date: Date
    }]
});

let Deposit = mongoose.model("Deposit", depositSchema)

module.exports = Deposit;