let mongoose = require('mongoose');
let Schema = mongoose.Schema;

let depositSchema = new Schema({
    //deposit id auto generated by mongo
    transaction: [{
        amount: {
            type: Number,
            trim: true
        },
        date: {
            type: Date,
            trim: true
        },
        transactionID: {
            type: Number,
            trim: true,
            unique: true,
            required: true
        }
    }]
});

let Deposit = mongoose.model("Deposit", depositSchema)

module.exports = Deposit;