let mongoose = require('mongoose');
let Schema = mongoose.Schema;

let plaidAccountsSchema = new Schema({
    // Link unique UserId as extra security.
    userId: {
        type: String,
        required: true
    },
    // Each access_token is unique to an Item(Account)
    // access_tokens do not expire. 
    accessToken: {
        type: String,
        required: true,
        unique: true,
        trim: true
    },
    institution: {
        name: {
            type: String,
            required: true
        },
        institution_id: {
            type: String,
            required: true
        }
    },
    //deposit id auto generated by mongo
    // Access: accounts.account_id
    account_id: {
        type: String,
        required: true,
        trim: true,
        unique: true
    },
    // Might be the same as account_id.
    item_id: {
        type: String,
        required: true,
        trim: true,
        unique: true
    },
    // Access: accounts.name
    accountName: {
        type: String,
        required: true
    },
    // example: "checking"
    // Access: accounts.type
    // example: "depository"
    // Used for Auth
    type: {
        type: String,
        required: true,
    },
    // Access: accounts.subtype
    // Used for Auth
    subtype: {
        type: String,
        required: true
    },
    // Access: numbers.ach.account
    // Used for Stripe to initiate ACH Transactions
    accountNumber: {
        type: String,
        trim: true,
    },
    // Access: numbers.ach.routing
    // Used for Stripe to initiate ACH Transactions
    routingNumber: {
        type: String,
        trim: true
    },
    // Access: numbers.ach.wire_routing
    // Used for Stripe to initiate ACH Transactions
    wire_routing: {
        type: String,
        trim: true
    }
});

let PlaidUserAccount = mongoose.model("PlaidUserAccount", plaidAccountsSchema);

module.exports = PlaidUserAccount;