let mongoose = require('mongoose');
let Schema = mongoose.Schema;

let roundedTransSchema = new Schema({

    //deposit id auto generated by mongo
    // name of the transaction that is being rounded up.
    transactionName: {
        type: String,
        required: true
    },
    // amount rounded up from transaction to be accessed from Stripe
    // to create the initial ACH Request.
    roundedAmount: {
        type: Number,
        required: true
    },
    transaction_id: {
        type: String,
        required: true,
        unique: true
    },
    date: {
        type: Date,
        required: true
    },
    userID: {
        type: String,
        required: true,
        trim: true
    }
});

let RoundedTrans = mongoose.model("RoundedTrans", roundedTransSchema)

module.exports = RoundedTrans;