let mongoose = require('mongoose');
let Schema = mongoose.Schema;

// Model to store Successful Stripe ACH Deposits
let StripeDeposSchema = new Schema({

    //deposit id auto generated by mongo
    userID: {
        type: String,
        required: true,
        trim: true
    },
    // Account_id associated to the account the transaction came from.
    account_id: {
        type: String,
        required: true
    },
    // name of the original transaction that was rounded up.
    transactionName: {
        type: String,
        required: true
    },
    // the original transaction amount.
    originalAmount: {
        type: Number,
        required: true
    },
    // The currency code for reference.
    currencyCode: {
        type: String,
        required: true
    },
    // Category of transaction.
    // For future use for User Savings Preferences & Settings.
    category: {
        type: Array,
        required: true
    },
    // amount deposited into Stripe from User Account from ACH.
    amountDeposited: {
        type: Number,
        trim: true
    },
    // The transaction_id associated to the completed posted ACH in Transaction History
    newTransactionId: {
        type: Number,
        trim: true,
        unique: true,
        required: true
    },
    // The original transaction_id associated to the transaction that was rounded up.
    originalTransId: {
        type: Number,
        trim: true,
        unique: true,
        required: true
    },
    originalTransactionDate: {
        type: Date,
        required: true
    },
    // Date that Stripe receives the rounded up amount.
    dateCompleted: {
        type: Date,
        required: true
    }
});

let StripeDepos = mongoose.model("StripeDepos", StripeDeposSchema)

module.exports = StripeDepos;