let mongoose = require('mongoose');
let Schema = mongoose.Schema;

let transactionHistory = new Schema({
    //deposit id auto generated by mongo
    transaction: [{
        name: {
           type: String
        },
        amount: {
            type: Number
        },
        transaction_id: {
            type: String,
            unique: true
        },
        date: {
            type: Date
        }
    }]
});
