let mongoose = require('mongoose');
let Schema = mongoose.Schema;

let transactionHistory = new Schema({

    //deposit id auto generated by mongo
    name: {
        type: String,
        required: true
    },
    amount: {
        type: Number,
        required: true
    },
    transaction_id: {
        type: String,
        required: true,
        unique: true
    },
    date: {
        type: Date,
        required: true
    }
});

let Transactions = mongoose.model("Transactions", transactionHistory);

module.exports = Transactions;