let mongoose = require('mongoose');
let Schema = mongoose.Schema;

let withdrawalSchema = new Schema({
    //withdrawal id auto generated by mongo
    amount: {
        type: Number,
        trim: true
    },
    date: {
        type: Date,
        trim: true
    },
    type: {
        type: String,
        trim: true
        //limit type options to purchase or personal withdrawal
    },
    notes: {
        type: String,
        trim: true
    },
    userID: {
        type: String,
        trim: true
    }
});

let Withdrawal = mongoose.model("Withdrawal", withdrawalSchema)

module.exports = Withdrawal;