let mongoose = require('mongoose');
let Schema = mongoose.Schema;

let withdrawalSchema = new Schema({
    //withdrawal id auto generated by mongo

    transaction: [{
        amount: {
            type: Number,
            trim: true
        },
        date: {
            type: Date,
            trim: true
        },
        reason: {
            type: String,
            trim: true
        },
        userID: {
            type: String,
            trim: true
        },
    }]
});

let Withdrawal = mongoose.model("Withdrawal", withdrawalSchema)

module.exports = Withdrawal;