let mongoose = require('mongoose');
let Schema = mongoose.Schema;

let roundedTransSchema = new Schema({

    //deposit id auto generated by mongo
    userID: {
        type: String,
        required: true,
        trim: true
    },
    account_id: {
        type: String,
        required: true
    },

    name: {
        type: String,
        trim: true
    },
    // name of the transaction that is being rounded up.
    transactionName: {
        type: String,
        required: true
    },
    
    // The currency code for reference.
    currencyCode: {
        type: String,
        required: true
    },

    // Category of transaction.
    // For future use for User Savings Preferences & Settings.
    category: {
        type: Array,
        required: true
    },

    date: {
        type: Date,
        required: true
    },
    
    // Original transaction amount.
    originalAmount: {
        type: Number,
        required: true
    },
    // amount rounded up from transaction to be accessed from Stripe
    // to create the initial ACH Request.
    roundedAmount: {
        type: Number,
        required: true
    },
    transaction_id: {
        type: String,
        required: true,
        unique: true
    }
});

let RoundedTrans = mongoose.model("RoundedTrans", roundedTransSchema)

module.exports = RoundedTrans;