    
let mongoose = require('mongoose');
let Schema = mongoose.Schema;

// Model to store Successful Stripe ACH Deposits
let StripeDeposSchema = new Schema({

    //deposit id auto generated by mongo
    userID: {
        type: String,
        required: true,
        trim: true
    },
    // name of the original transaction that was rounded up.
    transactionNames: {
        type: Array,
        required: true
    },
    // amount deposited into Stripe from User Account from ACH.
    amountDeposited: {
        type: Number,
        trim: true
    },
    depositDate: {
        type: Date,
        trim: true
    },
    // The transaction_id associated to the completed posted ACH in Transaction History
    TransactionId: {
        type: String,
        trim: true,
        unique: true,
        required: true
    },
    // The original\ transaction_id associated to the transaction that was rounded up.
    originalTransIds: {
        type: Array,
        trim: true,
        unique: true,
        required: true
    }
});

let StripeDepos = mongoose.model("StripeDepos", StripeDeposSchema)

module.exports = StripeDepos;