let mongoose = require('mongoose');
let Schema = mongoose.Schema;

let withdrawReqSchema = new Schema({

    //withdrawal id auto generated by mongo
    userID: {
        type: String,
        required: true,
        trim: true
    },
    withdrawalAmount: {
        type: Number,
        required: true,
        trim: true
    },
    withdrawDate: {
        type: Date,
        required: true,
        trim: true
    },
    reason: {
        type: String,
        required: true,
        trim: true
        // validate: radio button where we can track
    }
});

let WithdrawRequest = mongoose.model("WithdrawRequest", withdrawReqSchema)

module.exports = WithdrawRequest;